#!/bin/sh
set -e
cd "$(dirname "$0")"

case $1 in
sync)
    nvim -c 'autocmd User PackerComplete quitall' -c 'PackerSync'
    ;;
compile)
    nvim --headless -c 'autocmd User PackerCompileDone quitall' -c 'PackerCompile'
    ;;
moon)
    rm -rfv lua
    cd moon
    moonc -t ../lua .
    ;;
watch)
    exec watchexec -rcw moon ./update
    ;;
*)
    ./update moon
    ./update compile
    ;;
esac
